### ISSUE TITLE
`calculateWormholedPosition` is not correct

### ISSUE THREAD

**Issue by cbou** [cibernox/ember-basic-dropdown#257]
When calling `calculateWormholedPosition` the content is not at his final position which can impact `trigger.getBoundingClientRect()`.

Should we not first attach the `content` to the body and then call `calculateWormholedPosition`?

**Comment by cibernox** [comment]
Can you provide a reproduction example of the issue?

**Comment by cbou** [comment]
Yes, sorry I don't have a twiddle because I don't know how to import module there.

```hbs
<div class="container">
	<div class="container-relative">
		{{#basic-dropdown matchTriggerWidth=true as |dropdown|}}
			{{#dropdown.trigger}}
				<div class="trigger">
					Click me
				</div>
			{{/dropdown.trigger}}
			{{#dropdown.content}}
				<div class="content">
					Hello
				</div>
			{{/dropdown.content}}
		{{/basic-dropdown}}
	</div>
</div>
```

```css
.container {
	background: blue;
	height: 100px;
	width: 300px;
	overflow: auto;
}

.container-relative {
	position: relative;
}

.trigger {
	background: green;
}

.content {
	background: red;
	min-width: 25px;
	height: 300px;
}
```

Result is 
<img width="326" alt="screen shot 2017-04-06 at 00 59 42" src="https://cloud.githubusercontent.com/assets/611389/24730540/75f9674e-1a64-11e7-809d-a1c48ee5504a.png">

But it should be
<img width="313" alt="screen shot 2017-04-06 at 01 01 05" src="https://cloud.githubusercontent.com/assets/611389/24730557/88f5c9aa-1a64-11e7-908e-2b0417266178.png">
